import './globals.css'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import SessionProvider from "@/libs/clientServerSide"
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'] , weight:["100","200","300"]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <SessionProvider session={session}>
      <body className={poppins.className}>
        {children}
        </body>
     </SessionProvider>
    </html>
  )
}
